### ISSUE TITLE
ValueError: stoi

### ISSUE THREAD

**Issue by Shivangi1010** [LiyrAstroph/pyCALI#3]
Hi,

I was trying to work on my dataset, although I am encountering this issue.
Please, let me know what should I edit.

**Comment by liyropt** [comment]
This error occurs when the code cannot  get the number of points of each data code.  Check the format of your input data and make sure it has the appropriate format, see https://pycali.readthedocs.io/en/latest/getting_started.html#format-of-input-data-files. 

Also, PyCALI provides a function to create formatted data files from a Python dict. 

import pycali
pycali.format(fname, data)

Here, "fname" is the file name to generate, "data" is a python dict that stores the data, in which the keys represent the codes.

**Comment by Shivangi1010** [comment]
thank you!
