### ISSUE TITLE
error: Warning in mod(double, double) -1.274569e+00

### ISSUE THREAD

**Issue by Shivangi1010** [LiyrAstroph/pyCALI#4]
Hi,

I ran the sample data which is working perfectly.
However, when I ran it with my data, the mcmc is giving this warning and the code terminates there.
My data looks like this:
# A 28
59648.993439432874 1.398 0.015
59648.99722070602 1.642 0.016
59649.05480081018 1.379 0.017
............................
#B 19
# B 19
59648.95326388889 3.15 0.006
59648.96792824074 3.235 0.006
59648.98232638889 3.363 0.007
...........
Is there any specific instructions for the format of a data?
I have jumbled the data in so many different ways, and I could not perceive any information regarding how and what is required to not get a negative value?

**Comment by liyropt** [comment]
This error occurs in doing MCMC sampling, which indicates that the format of the input data file is fine, but there might be some problems with the data itself, such as a zero error, duplicated data points, or something else.   I cannot pinpoint the exact problem at this moment.   If you send me your data (through email), I may take a deep look.

**Comment by Shivangi1010** [comment]
Alright I will try to check and let you know.

Thank you!
Shivangi Pandey.

**Comment by liyropt** [comment]
The issue is due to the time length of the light curve is shorter than "tau_range_low". 
Set a smaller "tau_range_low" or use the new version of the code.

**Comment by Shivangi1010** [comment]
Alright Thank you!
